### ISSUE TITLE
Allocating large in-memory arrays

### ISSUE THREAD

**Issue by dkulagin** [omry/banana#3]
I am an NLP research engineer and I encounter the following use cases on a regular basis:
1. Loading large binary files with integers into memory (with more than 2Gb elements).
2. Accessing particular elements of those "big arrays" by index.
3. Copying continuous areas into regular Java arrays, mostly char arrays. (E.g. if I have a large corpora consisting of sentences and would like to have random in-memory access).

How can Banana help me?

**Comment by omry** [comment]
I am not sure Banana is the right tool for what you are describing.
Have you considered research environment like Torch (or Pytorch)?

If you want to try, take a look at the following:
Read about block allocators here:
https://github.com/omry/banana/wiki/Block-Allocators

Take a look at net.yadan.banana.memory.block.BigBlockAllocator, it implements the interfaces you need to set and get ints to a larger than 2GB elements array.

All operations are on allocated blocks, so you need to have a notion of a block of allocated memory.
To copy int arrays back and forth use setInts and getInts:
https://github.com/omry/banana/blob/master/banana/src/net/yadan/banana/memory/IPrimitiveAccess.java#L146-L169

There are similar functions to copy into char arrays.
Remember that underlying arrays are int[] arrays so there may be some small holes, but as lost as you are using the APIs above it should be fine.

BlockAllocators are memory managers for fixed size blocks (K ints per block).
Before using a block you need to call malloc to get a pointer to that block.
typically those blocks are not huge (IE: you will allocate many small blocks, not one huge block of 4GB ints).
